### PR TITLE
Merge and delete unused branch `pldi20`

### PR DESCRIPTION
**Pull request by siddharth-krishna**
I think we can delete this branch now that we have the `pldi_2020` tag and have also moved the PLDI '20 paper's proofs to the `template-proofs` repository.

### CODE REVIEW

**Comment by siddharth-krishna** [comment]
Should we also delete the files under `tests/spl/flows/` now that they're the other repo? Just to reduce duplication and possible confusion about which version is up-to-date.

**Comment by wies** [comment]
I am wondering whether we should at least keep the formalization of the flow framework around. One other advantage of having some version of these files here is that we can include them in the regression tests.

**Comment by siddharth-krishna** [comment]
Ah yes, that's a good point. The CI in `template-proofs` check against a fixed version of Grasshoper. Okay, let's keep them around.

(Btw, I don't think they're in the tests at the moment..)

**Comment by siddharth-krishna** [comment]
FYI, I've added the PLDI'20 test script to the regression tests in the `symb-exec` branch.

**Pull request merged**
